#!/bin/bash

# Update system packages
sudo dnf update -y
sudo dnf install tree vim nano wget git -y
sudo swapoff -a
sudo sed -i '/ swap / s/^\(.*\)$/#\1/' /etc/fstab

# Firewall setup
sudo dnf install firewalld -y
sudo systemctl start firewalld
sudo systemctl enable firewalld
sudo firewall-cmd --state
sudo firewall-cmd --permanent --add-port=25/tcp       # SMTP (Port 25)
sudo firewall-cmd --permanent --add-port=3000-10000/tcp  # Custom TCP (Port range 3000 - 10000)
sudo firewall-cmd --permanent --add-port=80/tcp       # HTTP (Port 80)
sudo firewall-cmd --permanent --add-port=443/tcp      # HTTPS (Port 443)
sudo firewall-cmd --permanent --add-port=22/tcp       # SSH (Port 22)
sudo firewall-cmd --permanent --add-port=6443/tcp     # Custom TCP (Port 6443)
sudo firewall-cmd --permanent --add-port=465/tcp      # SMTPS (Port 465)
sudo firewall-cmd --permanent --add-port=30000-32767/tcp  # Custom TCP (Port range 30000 - 32767)
sudo firewall-cmd --permanent --add-port=9100/tcp     # Custom TCP (Port 9100)
sudo firewall-cmd --permanent --add-port=10250/tcp
sudo firewall-cmd --permanent --add-port=8080/tcp     # Custom TCP (Port 8080)
sudo firewall-cmd --permanent --add-port=8081/tcp     # Custom TCP (Port 8081)
sudo firewall-cmd --permanent --add-port=1000-2000/tcp   # Custom TCP (Port range 1000 - 2000)
sudo firewall-cmd --reload

# Install Docker
sudo dnf install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
sudo systemctl enable docker
sudo systemctl start docker
sudo chmod 666 /var/run/docker.sock

# Containerd setup
sudo modprobe overlay
sudo modprobe br_netfilter

# Configure modules for Containerd
sudo tee /etc/modules-load.d/containerd.conf <<EOF
overlay
br_netfilter
EOF

# Configure sysctl settings for Kubernetes
sudo tee /etc/sysctl.d/kubernetes.conf <<EOF
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF
sysctl --system

# Add Docker repository and update packages
sudo curl -fsSL https://download.docker.com/linux/centos/gpg | sudo gpg --import -
sudo tee /etc/yum.repos.d/docker-ce.repo <<-'EOF'
[docker-ce-stable]
name=Docker CE Stable - $basearch
baseurl=https://download.docker.com/linux/centos/7/x86_64/stable
enabled=1
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg
EOF
sudo dnf update -y

# Remove exclude rules for Kubernetes packages
sudo sed -i '/exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni/d' /etc/yum.repos.d/kubernetes.repo

# Install Kubernetes components
sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
EOF
sudo yum install -y kubelet kubeadm kubectl
sudo systemctl restart containerd
sudo systemctl enable kubelet
